In [1]:
url = 'https://www.serialupdates.me/shark-tank-india-investors-names-sony-tv-new-show-entrepreneurs-list/'

In [2]:
import os

In [3]:
os.chdir('C:\Scripting')

In [4]:
from selenium import webdriver
from bs4 import BeautifulSoup
import requests

In [5]:
browser = webdriver.Firefox()

In [6]:
browser.get(url)

In [8]:
html = browser.page_source

In [10]:
soup = BeautifulSoup(html,'html.parser')

In [16]:
soup.select('figure.wp-block-table.is-style-stripes')[1].find_all('thead')[0].find_all('th')[0].text.strip()

'Sr No.'

In [17]:
table = soup.select('figure.wp-block-table.is-style-stripes')[1]

In [19]:
thead = [i.text.strip() for i in table.find_all('th')]
thead

['Sr No.',
 'Entrepreneur Name',
 'From',
 'Business',
 'Deal',
 'Original Ask',
 'Final Offer',
 'Investors']

In [23]:
import pandas as pd

In [32]:
def shark():
    thead = [i.text.strip() for i in table.find_all('th')]
    data=[]
    for a in soup.select('figure.wp-block-table.is-style-stripes')[1].tbody.find_all('tr'):
        data.append([i.text.strip() for i in a.find_all('td')])
    df = pd.DataFrame(data)
    df.columns = thead
    return df

In [46]:
df1 = shark()
df1.style.hide(axis='index')

In [29]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117 entries, 0 to 116
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No.             117 non-null    object
 1   Entrepreneur Name  117 non-null    object
 2   From               117 non-null    object
 3   Business           117 non-null    object
 4   Deal               117 non-null    object
 5   Original Ask       117 non-null    object
 6   Final Offer        117 non-null    object
 7   Investors          117 non-null    object
dtypes: object(8)
memory usage: 7.4+ KB

In [48]:
df1["Sr No."] = pd.to_numeric(df1["Sr No."])

In [49]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117 entries, 0 to 116
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No.             117 non-null    int64
 1   Entrepreneur Name  117 non-null    object
 2   From               117 non-null    object
 3   Business           117 non-null    object
 4   Deal               117 non-null    object
 5   Original Ask       117 non-null    object
 6   Final Offer        117 non-null    object
 7   Investors          117 non-null    object
dtypes: int64(1), object(7)
memory usage: 7.4+ KB

In [47]:
df1.to_csv("Shark Tank Investor Details.csv",index=False)